# Generated by Django 3.2.7 on 2021-10-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todos_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='todo.todos')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
            ],
        ),
        migrations.RemoveField(
            model_name='todos',
            name='qr_code',
        ),
    ]
